### ISSUE TITLE
Create flatpak package

### ISSUE THREAD

**Issue by mdtrooper** [mdtrooper/Fallen-leaves#3]

**Comment by mdtrooper** [comment]
The https://github.com/endlessm/electron-installer-flatpak does not run with sdk 1.6.

I reopen this issue and I set out the version. 


```
md@speccy-laptop:/media/md/1TB/proyectos/Fallen-leaves$ DEBUG=* npx electron-installer-flatpak --src dist/fallen-leaves-linux-x64/ --dest dist/ --arch x64
Creating package (this may take a while)
  electron-installer-flatpak Reading package metadata from dist/fallen-leaves-linux-x64/resources/app/package.json +0ms
  electron-installer-flatpak Creating package with options
  electron-installer-flatpak {
  electron-installer-flatpak   "src": "dist/fallen-leaves-linux-x64/",
  electron-installer-flatpak   "dest": "dist/",
  electron-installer-flatpak   "arch": "x64",
  electron-installer-flatpak   "id": "com.github.fallen-leaves",
  electron-installer-flatpak   "productName": "fallen-leaves",
  electron-installer-flatpak   "genericName": "fallen-leaves",
  electron-installer-flatpak   "description": "Fallen leaves is a simple slideshow viewer, the photos shows as falling leaves in the autumn.",
  electron-installer-flatpak   "branch": "master",
  electron-installer-flatpak   "base": "io.atom.electron.BaseApp",
  electron-installer-flatpak   "baseVersion": "master",
  electron-installer-flatpak   "baseFlatpakref": "https://s3-us-west-2.amazonaws.com/electron-flatpak.endlessm.com/electron-base-app-master.flatpakref",
  electron-installer-flatpak   "runtime": "org.freedesktop.Platform",
  electron-installer-flatpak   "runtimeVersion": "1.4",
  electron-installer-flatpak   "runtimeFlatpakref": "https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-runtime-1.4.flatpakref",
  electron-installer-flatpak   "sdk": "org.freedesktop.Sdk",
  electron-installer-flatpak   "sdkFlatpakref": "https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-sdk-1.4.flatpakref",
  electron-installer-flatpak   "finishArgs": [
  electron-installer-flatpak     "--socket=x11",
  electron-installer-flatpak     "--share=ipc",
  electron-installer-flatpak     "--device=dri",
  electron-installer-flatpak     "--socket=pulseaudio",
  electron-installer-flatpak     "--filesystem=home",
  electron-installer-flatpak     "--filesystem=/tmp",
  electron-installer-flatpak     "--share=network",
  electron-installer-flatpak     "--talk-name=org.freedesktop.Notifications"
  electron-installer-flatpak   ],
  electron-installer-flatpak   "modules": [],
  electron-installer-flatpak   "bin": "fallen-leaves",
  electron-installer-flatpak   "icon": "/media/md/1TB/proyectos/Fallen-leaves/node_modules/electron-installer-flatpak/resources/icon.png",
  electron-installer-flatpak   "files": [],
  electron-installer-flatpak   "symlinks": [],
  electron-installer-flatpak   "categories": [
  electron-installer-flatpak     "GNOME",
  electron-installer-flatpak     "GTK",
  electron-installer-flatpak     "Utility"
  electron-installer-flatpak   ],
  electron-installer-flatpak   "mimeType": []
  electron-installer-flatpak } +4ms
  electron-installer-flatpak Creating temporary directory +1ms
  electron-installer-flatpak Creating contents of package +6ms
  electron-installer-flatpak Creating desktop file at /tmp/electron-119618-15516-4h8fiz.ragow/com.github.fallen-leaves_undefined_x64/share/applications/com.github.fallen-leaves.desktop +0ms
  electron-installer-flatpak Generating template from /media/md/1TB/proyectos/Fallen-leaves/node_modules/electron-installer-flatpak/resources/desktop.ejs +1ms
  electron-installer-flatpak Creating icon file at /tmp/electron-119618-15516-4h8fiz.ragow/com.github.fallen-leaves_undefined_x64/share/pixmaps/com.github.fallen-leaves.png +1ms
  electron-installer-flatpak Creating copyright file at /tmp/electron-119618-15516-4h8fiz.ragow/com.github.fallen-leaves_undefined_x64/share/doc/com.github.fallen-leaves/copyright +1ms
  electron-installer-flatpak Reading license file from dist/fallen-leaves-linux-x64/LICENSE +1ms
  electron-installer-flatpak Copying application to /tmp/electron-119618-15516-4h8fiz.ragow/com.github.fallen-leaves_undefined_x64/lib/com.github.fallen-leaves +0ms
  electron-installer-flatpak Generated template from /media/md/1TB/proyectos/Fallen-leaves/node_modules/electron-installer-flatpak/resources/desktop.ejs
  electron-installer-flatpak [Desktop Entry]
  electron-installer-flatpak Name=fallen-leaves
  electron-installer-flatpak Comment=Fallen leaves is a simple slideshow viewer, the photos shows as falling leaves in the autumn.
  electron-installer-flatpak GenericName=fallen-leaves
  electron-installer-flatpak Exec=fallen-leaves %U
  electron-installer-flatpak Icon=com.github.fallen-leaves
  electron-installer-flatpak Type=Application
  electron-installer-flatpak StartupNotify=true
  electron-installer-flatpak Categories=GNOME;GTK;Utility;
  electron-installer-flatpak 
  electron-installer-flatpak  +10ms
  electron-installer-flatpak Creating package at dist/com.github.fallen-leaves_master_x64.flatpak +1s
  flatpak-bundler Using manifest...
  flatpak-bundler {
  flatpak-bundler   "id": "com.github.fallen-leaves",
  flatpak-bundler   "branch": "master",
  flatpak-bundler   "base": "io.atom.electron.BaseApp",
  flatpak-bundler   "base-version": "master",
  flatpak-bundler   "base-flatpakref": "https://s3-us-west-2.amazonaws.com/electron-flatpak.endlessm.com/electron-base-app-master.flatpakref",
  flatpak-bundler   "runtime": "org.freedesktop.Platform",
  flatpak-bundler   "runtime-version": "1.4",
  flatpak-bundler   "runtime-flatpakref": "https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-runtime-1.4.flatpakref",
  flatpak-bundler   "sdk": "org.freedesktop.Sdk",
  flatpak-bundler   "sdk-flatpakref": "https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-sdk-1.4.flatpakref",
  flatpak-bundler   "finish-args": [
  flatpak-bundler     "--socket=x11",
  flatpak-bundler     "--share=ipc",
  flatpak-bundler     "--device=dri",
  flatpak-bundler     "--socket=pulseaudio",
  flatpak-bundler     "--filesystem=home",
  flatpak-bundler     "--filesystem=/tmp",
  flatpak-bundler     "--share=network",
  flatpak-bundler     "--talk-name=org.freedesktop.Notifications"
  flatpak-bundler   ],
  flatpak-bundler   "command": "fallen-leaves",
  flatpak-bundler   "files": [
  flatpak-bundler     [
  flatpak-bundler       "/tmp/electron-119618-15516-4h8fiz.ragow/com.github.fallen-leaves_undefined_x64",
  flatpak-bundler       "/"
  flatpak-bundler     ]
  flatpak-bundler   ],
  flatpak-bundler   "symlinks": [
  flatpak-bundler     [
  flatpak-bundler       "/lib/com.github.fallen-leaves/fallen-leaves",
  flatpak-bundler       "/bin/fallen-leaves"
  flatpak-bundler     ]
  flatpak-bundler   ],
  flatpak-bundler   "extra-exports": [
  flatpak-bundler     "/share/pixmaps/com.github.fallen-leaves.png"
  flatpak-bundler   ],
  flatpak-bundler   "modules": []
  flatpak-bundler } +0ms
  flatpak-bundler Using options...
  flatpak-bundler {
  flatpak-bundler   "arch": "x86_64",
  flatpak-bundler   "bundle-path": "/media/md/1TB/proyectos/Fallen-leaves/dist/com.github.fallen-leaves_master_x64.flatpak",
  flatpak-bundler   "working-dir": "/var/tmp/tmp-15516q9XnuAtEAHeU",
  flatpak-bundler   "build-dir": "/var/tmp/tmp-15516q9XnuAtEAHeU/build",
  flatpak-bundler   "repo-dir": "/var/tmp/tmp-15516q9XnuAtEAHeU/repo",
  flatpak-bundler   "manifest-path": "/var/tmp/tmp-15516q9XnuAtEAHeU/manifest.json",
  flatpak-bundler   "extra-flatpak-builder-args": [],
  flatpak-bundler   "extra-flatpak-build-bundle-args": [],
  flatpak-bundler   "extra-flatpak-build-export-args": [],
  flatpak-bundler   "clean-tmpdirs": true,
  flatpak-bundler   "auto-install-runtime": true,
  flatpak-bundler   "auto-install-sdk": true,
  flatpak-bundler   "auto-install-base": true
  flatpak-bundler } +1ms
  flatpak-bundler Ensuring runtime is up to date +1ms
  flatpak-bundler Checking for install of org.freedesktop.Platform +0ms
  flatpak-bundler $ flatpak info --show-commit --user org.freedesktop.Platform/x86_64/1.4 +0ms
  flatpak-bundler $ flatpak info --show-commit --system org.freedesktop.Platform/x86_64/1.4 +11ms
  flatpak-bundler 1> 
  flatpak-bundler Note that the directories 
  flatpak-bundler  +39ms
  flatpak-bundler 1> 
  flatpak-bundler '/var/lib/flatpak/exports/share'
  flatpak-bundler '/home/md/.local/share/flatpak/exports/share'
  flatpak-bundler 
  flatpak-bundler are not in the search path set by the XDG_DATA_DIRS environment variable, so
  flatpak-bundler applications installed by Flatpak may not appear on your desktop until the
  flatpak-bundler session is restarted.
  flatpak-bundler 
  flatpak-bundler  +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +3ms
  flatpak-bundler 1> Note +0ms
  flatpak-bundler 1>  that +0ms
  flatpak-bundler 1>  the +0ms
  flatpak-bundler 1>  directories 
  flatpak-bundler 
  flatpak-bundler  +1ms
  flatpak-bundler 1> '/var/lib/flatpak/exports/share'
  flatpak-bundler '/home/md/.local/share/flatpak/exports/share'
  flatpak-bundler 
  flatpak-bundler are not in the search path set by the XDG_DATA_DIRS environment variable, so
  flatpak-bundler applications installed by Flatpak may not appear on your desktop until the
  flatpak-bundler session is restarted.
  flatpak-bundler 
  flatpak-bundler  +0ms
  flatpak-bundler 2> error: org.freedesktop.Platform/x86_64/1.4 not installed
  flatpak-bundler  +79ms
  flatpak-bundler 2> error: org.freedesktop.Platform/x86_64/1.4 not installed
  flatpak-bundler  +19ms
  flatpak-bundler No install of org.freedesktop.Platform found, trying to install from https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-runtime-1.4.flatpakref +3ms
  flatpak-bundler $ flatpak install --user --no-deps --arch x86_64 --from https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-runtime-1.4.flatpakref +0ms
  flatpak-bundler 1> 
  flatpak-bundler Note that the directories 
  flatpak-bundler 
  flatpak-bundler '/var/lib/flatpak/exports/share'
  flatpak-bundler '/home/md/.local/share/flatpak/exports/share'
  flatpak-bundler 
  flatpak-bundler are not in the +36ms
  flatpak-bundler 1>  search path set by the XDG_DATA_DIRS environment variable, so
  flatpak-bundler applications installed by Flatpak may not appear on your desktop until the
  flatpak-bundler session is restarted.
  flatpak-bundler 
  flatpak-bundler  +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +3s
  flatpak-bundler 1> 
  flatpak-bundler  1.	   	org.freedesktop.Platform	x86_64	1.4	platform-origin	< 190,4 MB
  flatpak-bundler  2.	   	org.freedesktop.Platform.Locale	x86_64	1.4	platform-origin	< 90,4 MB (partial)
  flatpak-bundler 
  flatpak-bundler Proceed with these changes to the user installation? [Y/n]: n
  flatpak-bundler  +0ms
  flatpak-bundler Ensuring sdk is up to date +16ms
  flatpak-bundler Checking for install of org.freedesktop.Sdk +0ms
  flatpak-bundler $ flatpak info --show-commit --user org.freedesktop.Sdk/x86_64/ +0ms
  flatpak-bundler $ flatpak info --show-commit --system org.freedesktop.Sdk/x86_64/ +11ms
  flatpak-bundler 1> 
  flatpak-bundler  +46ms
  flatpak-bundler 1> Note +0ms
  flatpak-bundler 1> 
  flatpak-bundler Note that the directories 
  flatpak-bundler 
  flatpak-bundler '/var/lib/flatpak/exports/share'
  flatpak-bundler '/home/md/.local/share/flatpak/exports/share'
  flatpak-bundler 
  flatpak-bundler are not in the search path set by the XDG_DATA_DIRS environment variable, so
  flatpak-bundler applications installed by Flatpak may not appear on your desktop until the
  flatpak-bundler session is restarted.
  flatpak-bundler 
  flatpak-bundler  +1ms
  flatpak-bundler 1>  that +1ms
  flatpak-bundler 1>  the +8ms
  flatpak-bundler 1>  directories +0ms
  flatpak-bundler 1>   +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +0ms
  flatpak-bundler 1> '/var/lib/flatpak/exports/share' +1ms
  flatpak-bundler 1> 
  flatpak-bundler  +0ms
  flatpak-bundler 1> '/home/md/.local/share/flatpak/exports/share' +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +4ms
  flatpak-bundler 1> 
  flatpak-bundler  +1ms
  flatpak-bundler 1> are not in the search +0ms
  flatpak-bundler 1>  path set by the XDG_DATA_DIRS environment variable, so
  flatpak-bundler applications installed by Flatpak may not appear on your desktop until the
  flatpak-bundler session is restarted.
  flatpak-bundler 
  flatpak-bundler  +0ms
  flatpak-bundler 2> error: org.freedesktop.Sdk/x86_64/*unspecified* not installed
  flatpak-bundler  +53ms
  flatpak-bundler 2> error: Multiple branches available for org.freedesktop.Sdk, you must specify one of: org.freedesktop.Sdk/x86_64/1.6, org.freedesktop.Sdk/x86_64/18.08
  flatpak-bundler  +68ms
  flatpak-bundler No install of org.freedesktop.Sdk found, trying to install from https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-sdk-1.4.flatpakref +2ms
  flatpak-bundler $ flatpak install --user --no-deps --arch x86_64 --from https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-sdk-1.4.flatpakref +0ms
  flatpak-bundler 1> 
  flatpak-bundler Note that the directories 
  flatpak-bundler 
  flatpak-bundler '/var/lib/flatpak/exports/share'
  flatpak-bundler '/home/md/.local/share/flatpak/exports/share'
  flatpak-bundler 
  flatpak-bundler are not in the search path +49ms
  flatpak-bundler 1>  set by the XDG_DATA_DIRS environment variable, so
  flatpak-bundler applications installed by Flatpak may not appear on your desktop until the
  flatpak-bundler session is restarted.
  flatpak-bundler 
  flatpak-bundler  +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +2s
  flatpak-bundler 1> 
  flatpak-bundler  1.	   	org.freedesktop.Sdk	x86_64	1.4	sdk-origin	< 475,3 MB
  flatpak-bundler  2.	   	org.freedesktop.Sdk.Locale	x86_64	1.4	sdk-origin	< 90,4 MB (partial)
  flatpak-bundler 
  flatpak-bundler Proceed with these changes to the user installation? [Y/n]: n
  flatpak-bundler  +1ms
  flatpak-bundler Ensuring base app is up to date +13ms
  flatpak-bundler Checking for install of io.atom.electron.BaseApp +1ms
  flatpak-bundler $ flatpak info --show-commit --user io.atom.electron.BaseApp/x86_64/master +0ms
  flatpak-bundler $ flatpak info --show-commit --system io.atom.electron.BaseApp/x86_64/master +9ms
  flatpak-bundler 1> 
  flatpak-bundler Note that the directories 
  flatpak-bundler  +35ms
  flatpak-bundler 1> 
  flatpak-bundler '/var/lib/flatpak/exports/share'
  flatpak-bundler '/home/md/.local/share/flatpak/exports/share'
  flatpak-bundler 
  flatpak-bundler are not in the search path set by the XDG_DATA_DIRS environment variable, so
  flatpak-bundler applications installed by Flatpak may not appear on your desktop until the
  flatpak-bundler session is restarted.
  flatpak-bundler 
  flatpak-bundler  +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +28ms
  flatpak-bundler 1> Note +1ms
  flatpak-bundler 1>  that +0ms
  flatpak-bundler 1>  the +0ms
  flatpak-bundler 1>  directories +0ms
  flatpak-bundler 1>   +1ms
  flatpak-bundler 1> 
  flatpak-bundler  +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +1ms
  flatpak-bundler 1> '/var/lib/flatpak/exports/share' +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +1ms
  flatpak-bundler 1> '/home/md/.local/share/flatpak/exports/share' +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +1ms
  flatpak-bundler 1> are +0ms
  flatpak-bundler 1>  not +0ms
  flatpak-bundler 1>  in +0ms
  flatpak-bundler 1>  the +0ms
  flatpak-bundler 1>  search +1ms
  flatpak-bundler 1>  path +0ms
  flatpak-bundler 1>  set +0ms
  flatpak-bundler 1>  by +0ms
  flatpak-bundler 1>  the +0ms
  flatpak-bundler 1>  XDG_DATA_DIRS +0ms
  flatpak-bundler 1>  environment +0ms
  flatpak-bundler 1>  variable, +1ms
  flatpak-bundler 1>  so +0ms
  flatpak-bundler 1> 
  flatpak-bundler applications +0ms
  flatpak-bundler 1>  installed +0ms
  flatpak-bundler 1>  by +1ms
  flatpak-bundler 1>  Flatpak +0ms
  flatpak-bundler 1>  may +0ms
  flatpak-bundler 1>  not +0ms
  flatpak-bundler 1>  appear +0ms
  flatpak-bundler 1>  on +0ms
  flatpak-bundler 1>  your +1ms
  flatpak-bundler 1>  desktop +0ms
  flatpak-bundler 1>  until +0ms
  flatpak-bundler 1>  the +0ms
  flatpak-bundler 1> 
  flatpak-bundler session +0ms
  flatpak-bundler 1>  is restarted.
  flatpak-bundler 
  flatpak-bundler  +2ms
  flatpak-bundler 2> error: io.atom.electron.BaseApp/x86_64/master not installed
  flatpak-bundler  +32ms
  flatpak-bundler 2> error: io.atom.electron.BaseApp/x86_64/master not installed
  flatpak-bundler  +76ms
  flatpak-bundler No install of io.atom.electron.BaseApp found, trying to install from https://s3-us-west-2.amazonaws.com/electron-flatpak.endlessm.com/electron-base-app-master.flatpakref +2ms
  flatpak-bundler $ flatpak install --user --no-deps --arch x86_64 --from https://s3-us-west-2.amazonaws.com/electron-flatpak.endlessm.com/electron-base-app-master.flatpakref +1ms
  flatpak-bundler 1> 
  flatpak-bundler  +40ms
  flatpak-bundler 1> Note +0ms
  flatpak-bundler 1>  that +1ms
  flatpak-bundler 1>  the +0ms
  flatpak-bundler 1>  directories +0ms
  flatpak-bundler 1>   +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +1ms
  flatpak-bundler 1> '/var/lib/flatpak/exports/share' +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +0ms
  flatpak-bundler 1> '/home/md/.local/share/flatpak/exports/share' +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +0ms
  flatpak-bundler 1> are +0ms
  flatpak-bundler 1>  not +1ms
  flatpak-bundler 1>  in +0ms
  flatpak-bundler 1>  the +0ms
  flatpak-bundler 1>  search +0ms
  flatpak-bundler 1>  path +0ms
  flatpak-bundler 1>  set +0ms
  flatpak-bundler 1>  by +0ms
  flatpak-bundler 1>  the +0ms
  flatpak-bundler 1>  XDG_DATA_DIRS +1ms
  flatpak-bundler 1>  environment +0ms
  flatpak-bundler 1>  variable, +0ms
  flatpak-bundler 1>  so +0ms
  flatpak-bundler 1> 
  flatpak-bundler applications +0ms
  flatpak-bundler 1>  installed +0ms
  flatpak-bundler 1>  by +0ms
  flatpak-bundler 1>  Flatpak +0ms
  flatpak-bundler 1>  may +1ms
  flatpak-bundler 1>  not +0ms
  flatpak-bundler 1>  appear +0ms
  flatpak-bundler 1>  on +0ms
  flatpak-bundler 1>  your +0ms
  flatpak-bundler 1>  desktop +0ms
  flatpak-bundler 1>  until +0ms
  flatpak-bundler 1>  the +0ms
  flatpak-bundler 1> 
  flatpak-bundler session +1ms
  flatpak-bundler 1>  is +0ms
  flatpak-bundler 1>  restarted. +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +0ms
  flatpak-bundler 1> 
  flatpak-bundler  +3s
  flatpak-bundler 1> 
  flatpak-bundler  1.	   	io.atom.electron.BaseApp	x86_64	master	baseapp-origin	< 7,9 MB
  flatpak-bundler  2.	   	io.atom.electron.BaseApp.Locale	x86_64	master	baseapp-origin	< 9,5 MB (partial)
  flatpak-bundler 
  flatpak-bundler Proceed with these changes to the user installation? [Y/n]: n
  flatpak-bundler  +0ms
  flatpak-bundler $ flatpak-builder --arch x86_64 --force-clean --build-only /var/tmp/tmp-15516q9XnuAtEAHeU/build /var/tmp/tmp-15516q9XnuAtEAHeU/manifest.json +14ms
  flatpak-bundler 2> 
  flatpak-bundler (flatpak-builder:15614): flatpak-builder-WARNING **: 11:22:45.847: Unknown property base-flatpakref for type BuilderManifest
  flatpak-bundler 
  flatpak-bundler (flatpak-builder:15614): flatpak-builder-WARNING **: 11:22:45.847: Unknown property runtime-flatpakref for type BuilderManifest
  flatpak-bundler  +58ms
  flatpak-bundler 2> 
  flatpak-bundler (flatpak-builder:15614): flatpak-builder-WARNING **: 11:22:45.847: Unknown property sdk-flatpakref for type BuilderManifest
  flatpak-bundler 
  flatpak-bundler (flatpak-builder:15614): flatpak-builder-WARNING **: 11:22:45.847: Unknown property files for type BuilderManifest
  flatpak-bundler 
  flatpak-bundler (flatpak-builder:15614): flatpak-builder-WARNING **: 11:22:45.847: Unknown property symlinks for type BuilderManifest
  flatpak-bundler 
  flatpak-bundler (flatpak-builder:15614): flatpak-builder-WARNING **: 11:22:45.847: Unknown property extra-exports for type BuilderManifest
  flatpak-bundler  +1ms
  flatpak-bundler 2> error: org.freedesktop.Sdk/x86_64/1.4 not installed
  flatpak-bundler  +99ms
  flatpak-bundler 2> Failed to init: Unable to find sdk org.freedesktop.Sdk version 1.4
  flatpak-bundler  +4ms
  electron-installer-flatpak Error creating package: flatpak-builder failed with status code 1 +9s
Error: flatpak-builder failed with status code 1
    at ChildProcess.child.on (/media/md/1TB/proyectos/Fallen-leaves/node_modules/flatpak-bundler/index.js:74:16)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5) 'Error: flatpak-builder failed with status code 1\n    at ChildProcess.child.on (/media/md/1TB/proyectos/Fallen-leaves/node_modules/flatpak-bundler/index.js:74:16)\n    at ChildProcess.emit (events.js:193:13)\n    at maybeClose (internal/child_process.js:999:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)'
```
